
FROM node:19 As Development

ENV NODE_ENV=development

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY prisma ./prisma/
COPY tsconfig.build.json ./
COPY tsconfig.json ./

RUN yarn install --production=false

COPY . .

EXPOSE 3000

CMD ["yarn", "start:client"]