
FROM node:19-alpine As Development

ENV NODE_ENV=development

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./
#COPY prisma ./prisma/


RUN yarn install --production=false

COPY client ./client/
COPY .env* ./
COPY config-overrides.js ./
COPY tsconfig.build.json ./
COPY tsconfig.json ./
COPY webpack-hmr.config.js ./

EXPOSE 3000

CMD ["yarn", "watch"]