
FROM node:19 As Development

ENV NODE_ENV=development

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY prisma ./prisma/
COPY tsconfig.build.json ./
COPY tsconfig.json ./

RUN yarn install --production=false

COPY . .

EXPOSE 3001

RUN yarn build:server;