
FROM node:19-alpine As Development

ENV NODE_ENV=development

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./
COPY prisma ./prisma/

RUN yarn install --production=false

COPY . .

EXPOSE 3000

CMD ["yarn", "watch"]