
FROM node:19-alpine As Development

ENV NODE_ENV=development

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY prisma ./prisma/

RUN yarn install --production=false

COPY . .

EXPOSE 3001

RUN yarn build:server;


FROM node:19-alpine As Production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY prisma ./prisma/

COPY --from=development /app/ .

EXPOSE 3001

CMD [ "yarn", "start:prod" ]